module.exports = {
  filepath: {
    1: "AngryBirds",
    2: "MissionMarsFiles",
    3: "MonkeyMultiplierFiles",
    4: "LetsMakeItRainFiles",
    5: "BowlingGameFiles",
    6: "ClockGameFiles",
    7: "AlienGameFiles",
    8: "AvengersGameFiles",
    9: "WhackAMoleFiles",
    10: "IncrediblesGameFiles",
    11: "ColorFunGameFiles",
    12: "SolarSystemGameFiles",
    13: "TemperatureConversionFiles",
    25: "AnimalHomeGameFiles",
    26: "DecimalGameFiles",
    27: "ZombieGameFiles",
    28: "CalculatorGameFiles",
    29: "CardGameFiles",
    30: "CashierGameFiles",
    31: "HitItFiles",
    32: "LifeCycleOfButterflyFiles",
    33: "MotuPatluGameFiles",
    34: "PhotosynthesisGameFiles",
    35: "PollutoGameFiles",
    36: "RecycleItFiles",
    37: "StatesThatMatterFiles",
    38: "TrashGameFiles",
    39: "FlappyGameFiles",
    40: "StepMeasureGameFiles"
  },
};
