name: Auto Build on Push

on:
  push:
    branches: [production]

jobs:
  build:
    env:
      CI: false
      GENERATE_SOURCEMAP: false
      NODE_ENV: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm ci
      - run: npm run build
