on:
  push:
    branches:
      - production
name: Deploy through FTP
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GENERATE_SOURCEMAP: false
      CI: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: install
        run: npm ci
      - name: build
        run: npm run build
      - name: sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ftp://ftp.funcbox.in:21/public_html
          username: funcbox_admin@funcbox.in
          password: FuncBox123*
          local-dir: ./build/
